version: '3.8'

services:
  orchestrator:
    image: swarm-orchestrator
    container_name: orchestrator
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  clientgen:
    image: clientgen-service
    container_name: clientgen
    ports:
      - "8011:8000"
    restart: unless-stopped
